### ISSUE TITLE
Handling continuous variables 

### ISSUE THREAD

**Issue by miranthajayatilake** [rcamino/multi-categorical-gans#5]
Hi,

Is there a method to handle continuous variables together with multi-categorical variables at the same time using your implementation? If not, are there any suggestions on how to do so?

Thanks for sharing this great code!

Cheers!

**Comment by rcamino** [comment]
Hi!

Thank you for your interest in the code :)

I've been working on combining this with continuous variables, and also using the models for other tasks like missing data imputation. You can check my pre-print if you want:

[Improving Missing Data Imputation with Deep Generative Models](https://arxiv.org/abs/1902.10666)

It's a work in progress (got rejected from ICML) but I will try to improve it and post the code soon.

**Comment by miranthajayatilake** [comment]
Thanks for the feedback and sharing your paper Ramiro. Looking forward to the improvements.
